//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineLink.DesktopClient.MachineLinkServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadProgramResponse", Namespace="http://schemas.datacontract.org/2004/07/MachineLink.Service")]
    [System.SerializableAttribute()]
    public partial class DownloadProgramResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Program {
            get {
                return this.ProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramField, value) != true)) {
                    this.ProgramField = value;
                    this.RaisePropertyChanged("Program");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MachineLinkServiceReference.IMachineLinkService")]
    public interface IMachineLinkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineLinkService/DownloadProgram", ReplyAction="http://tempuri.org/IMachineLinkService/DownloadProgramResponse")]
        MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse DownloadProgram();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMachineLinkService/DownloadProgram", ReplyAction="http://tempuri.org/IMachineLinkService/DownloadProgramResponse")]
        System.IAsyncResult BeginDownloadProgram(System.AsyncCallback callback, object asyncState);
        
        MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse EndDownloadProgram(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMachineLinkServiceChannel : MachineLink.DesktopClient.MachineLinkServiceReference.IMachineLinkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DownloadProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MachineLinkServiceClient : System.ServiceModel.ClientBase<MachineLink.DesktopClient.MachineLinkServiceReference.IMachineLinkService>, MachineLink.DesktopClient.MachineLinkServiceReference.IMachineLinkService {
        
        private BeginOperationDelegate onBeginDownloadProgramDelegate;
        
        private EndOperationDelegate onEndDownloadProgramDelegate;
        
        private System.Threading.SendOrPostCallback onDownloadProgramCompletedDelegate;
        
        public MachineLinkServiceClient() {
        }
        
        public MachineLinkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MachineLinkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachineLinkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachineLinkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<DownloadProgramCompletedEventArgs> DownloadProgramCompleted;
        
        public MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse DownloadProgram() {
            return base.Channel.DownloadProgram();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDownloadProgram(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDownloadProgram(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse EndDownloadProgram(System.IAsyncResult result) {
            return base.Channel.EndDownloadProgram(result);
        }
        
        private System.IAsyncResult OnBeginDownloadProgram(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDownloadProgram(callback, asyncState);
        }
        
        private object[] OnEndDownloadProgram(System.IAsyncResult result) {
            MachineLink.DesktopClient.MachineLinkServiceReference.DownloadProgramResponse retVal = this.EndDownloadProgram(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDownloadProgramCompleted(object state) {
            if ((this.DownloadProgramCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DownloadProgramCompleted(this, new DownloadProgramCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DownloadProgramAsync() {
            this.DownloadProgramAsync(null);
        }
        
        public void DownloadProgramAsync(object userState) {
            if ((this.onBeginDownloadProgramDelegate == null)) {
                this.onBeginDownloadProgramDelegate = new BeginOperationDelegate(this.OnBeginDownloadProgram);
            }
            if ((this.onEndDownloadProgramDelegate == null)) {
                this.onEndDownloadProgramDelegate = new EndOperationDelegate(this.OnEndDownloadProgram);
            }
            if ((this.onDownloadProgramCompletedDelegate == null)) {
                this.onDownloadProgramCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDownloadProgramCompleted);
            }
            base.InvokeAsync(this.onBeginDownloadProgramDelegate, null, this.onEndDownloadProgramDelegate, this.onDownloadProgramCompletedDelegate, userState);
        }
    }
}
